### ISSUE TITLE
Update README with how to play and interact

### ISSUE THREAD

**Issue by davidpelayo** [Mazagu/plantsvscreepers#1]
I'm trying to play with this (just saw the post [here](https://www.linkedin.com/posts/activity-6632276439536414720-_erw) but I can't get working (latest Chrome and Safari versions).

A few bits on how to use it would be helpful, so I can start collaborating with the project :)

Thanks!

**Comment by Mazagu** [comment]
Hi!
I'm planning to do a little refactoring and writting a little documentation. The code is plain javascript, you just need to download al the files, keeping the folder structure, and open the `index.html` in your browser.

Let me know if you get any errors in the console.

Regards!

**Comment by davidpelayo** [comment]
Good, it works shiny. Thanks.
